//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 15/6/4.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BeizierPath : NSObject

// Drawing Methods
+ (void)drawCanvas1;

@end
