//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 15/6/4.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "BeizierPath.h"


@implementation BeizierPath

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(52, 212)];
    [bezierPath addCurveToPoint: CGPointMake(348, 60) controlPoint1: CGPointMake(52, 212) controlPoint2: CGPointMake(321, 8)];
    [bezierPath addCurveToPoint: CGPointMake(-39, 80) controlPoint1: CGPointMake(375, 112) controlPoint2: CGPointMake(46, 70)];
    [bezierPath addCurveToPoint: CGPointMake(-83, 212) controlPoint1: CGPointMake(-124, 90) controlPoint2: CGPointMake(-102, 192)];
    [bezierPath addCurveToPoint: CGPointMake(41, 220) controlPoint1: CGPointMake(-64, 232) controlPoint2: CGPointMake(41, 220)];
    [UIColor.whiteColor setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];
}

@end
